from typing import Any, Protocol, Literal, List


class BaseInterface(Protocol):
    def print_user_message(self, message: Any) -> None: ...
    def print_agent_message(self, message: Any) -> None: ...
    def print_system_message(
        self, message: Any, type: Literal["info", "warning", "error"] = "info"
    ) -> None: ...
    def print_history(self, history: list) -> None: ...

    def input(self, message: str) -> str: ...
